### ISSUE TITLE
Help with shared key

### ISSUE THREAD

**Issue by cblavier** [jakobht/azurex#27]
Hey, thanks for your library 🙏

I'm a beginner with the Azure ecosystem, I'm more used to Amazon Web Services.

It looks like `Azurex.Authorization.SharedKey` is somewhat similar to AWS pre-signed URLS: can I use it to authorize a user to upload just one blob in a container?

Do you have any code samples regarding this feature?

**Comment by jakobht** [comment]
Hi
My understanding is that the shared key gives access to the full storage account, so this should only be used on the server side. I think it might be possible to use a Shared Access Signature for your purpose, see https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature

In the azure storage explorer I can manually create a Shared Access Signature using this dialog, and it looks like it allows for what you need (I'm sure you can create these programmatically):
![image](https://user-images.githubusercontent.com/580533/187156001-f927799a-3521-4f1a-83bb-99497a698ba3.png)

I do not have any experience with this, and the library does not currently support Shared Access Signatures, but PRs welcome :-) 

Hope it helps!

**Comment by cblavier** [comment]
I'm sorry I did not reply earlier, your answer definitely helps.
My Azure-related project is postponed by a few weeks, but I'm sure I'll have the opportunity to open a couple of PR :)
